### ISSUE TITLE
Schema.org errors

### ISSUE THREAD

**Issue by TheSDTM** [gnotaras/wordpress-add-meta-tags#16]
Hello. There are several errors after testing by Google Structured data testing tool.

<img width="590" alt="2015-12-13 12 34 12" src="https://cloud.githubusercontent.com/assets/13622053/11765918/8888510a-a197-11e5-96ad-84dca302d4e7.png">

1) I don't know why, but my Tool says that logo is wrong.

<img width="590" alt="2015-12-13 12 40 41" src="https://cloud.githubusercontent.com/assets/13622053/11765888/be08bcf8-a196-11e5-9588-adc98bec6199.png">
2) Incorrect image's url
3) There is no mainEntityOfPage tag.
How to solve this problems?
Thank you.

**Comment by gnotaras** [comment]
Hello,

I'm afraid I cannot reproduce these errors in my test website. Have you set the URL of the logo in the 'Default Image' box in the Add-meta-tags settings?

I also tried to check your web site using Google's Structured Data Testing tool, but no errors were reported. From what I can tell you have enabled a different plugin at this moment.

If possible, please activate Add-Meta-Tags only and re-check. Also, please let me know so I can check the site.

George

**Comment by gnotaras** [comment]
It has started showing me these errors. I'm working on a fix.

**Comment by TheSDTM** [comment]
Ok, what I did to solve: in my logo I created ImageObject (with name, url, etc.). I change urls of my pictures to contentUrl value. "mainEntityOfPage" - I added headline inside this attribute. And it works good

**Comment by gnotaras** [comment]
Hi, the resolution of the logo issue is correct. I'll need to think a little about the _mainEntityOfPage_. I'll keep you updated.

**Comment by gnotaras** [comment]
They seem to have left the validation of _mainEntityOfPage_ a bit vague, but I think the URL of the page is a better value.

**Comment by TheSDTM** [comment]
Ok, but what is wrong with images' urls? May be google think, that attachment page is like normal, regular site page?

**Comment by gnotaras** [comment]
I also just fixed this error with image urls. The error message is a little confusing. I used the URL to the image file for the _url_ attribute and the permalink of the attachment page in a _sameAs_ attribute.

**Comment by gnotaras** [comment]
Needs more work than I had initially thought... I might roll out a beta release. Would you be interested?

**Comment by TheSDTM** [comment]
Ok, I would try it

**Comment by gnotaras** [comment]
Hi @TheSDTM 

v2.10.1 has been released. All the aforementioned validation errors should now be fixed. There are still some errors about missing properties on embedded media, like youtube videos, but this is because WordPress doesn't stored much information about oEmbeds. AMT does not make any HTTP requests to fetch any such data, so these missing properties on embedded media will be there.

If you have updated, I'd appreciate some feedback.

Kind Regards,
George

**Comment by TheSDTM** [comment]
Ok, i will update it soon, and I will check website pages and create report for you

**Comment by gnotaras** [comment]
Hi, 2.10.1 seems like a good release. If you notice anything that does not work as expected, please feel free to add more comments here.

George
