### ISSUE TITLE
Schema Data for Video objects - Missing values

### ISSUE THREAD

**Issue by ULRaidX** [gnotaras/wordpress-add-meta-tags#18]
When embedding youtube videos it correctly generates the schema data However it is missing some vital values.

description:	missing and required
name:	missing and required
thumbnailUrl:	missing and required
uploadDate:	missing and required

Example schema embed. Removed first meta define so it displays correctly here. 

itemprop="video" itemscope itemtype="http://schema.org/VideoObject">
itemprop="embedURL" content="https://youtube.com/v/qslJQUMc9yA"/>
itemprop="playerType" content="application/x-shockwave-flash"/>
itemprop="width" content="640"/>
itemprop="height" content="480"/>

https://developers.google.com/structured-data/rich-snippets/videos?

**Comment by gnotaras** [comment]
Hello,

Regarding this issue, please check [this section in the FAQ](http://www.codetrax.org/projects/wp-add-meta-tags/wiki/FAQ#Google-Structured-Data-Validation-Tool-reports-missing-attributes-for-Youtube-videos-Why-dont-you-fix-it).

I'll now close this issue. Unless wordpress starts storing more information about the oEmbeds, there is nothing more I can do. I'm sorry about that..

George
