### ISSUE TITLE
Can twitter:image be configured for each post's image file?

### ISSUE THREAD

**Issue by soccermoviemom** [gnotaras/wordpress-add-meta-tags#22]
I just started using Add-Meta-Tags on my soccer movie review site. I tried setting the metadata for twitter cards, but I could only specify one image for the whole site.

Since each post contains a thumbnail for each movie, It would be nice if I could specify, using the wordpress admin interface, a specific name="twitter:image" value for each post. Is that possible? 

An example page is http://www.soccermoviemom.com/bounce-ball-2015

**Comment by gnotaras** [comment]
Hello,

May I ask how are you attaching your images to the posts? Please read more about the [Add-Meta-Tags fallback logic regarding images](http://www.codetrax.org/projects/wp-add-meta-tags/wiki/Metadata_Strategy#Images).

If you need more help, please feel free to ask.

Kind regards,
George

**Comment by gnotaras** [comment]
@soccermoviemom 

Hi Merijane,

I took a closer look at the metadata on your pages.

First, it seems that you have [this image](http://www.soccermoviemom.com/wp-content/uploads/2014/05/soccermoviemom-logo-diag-200x200px.jpg) as the URL of the default image in the Add-Meta-Tags settings.

Second, most probably the images that exist in your posts have been added manually using `<img ... />` HTML elements, without using the WP media library. This is fine, but Add-Meta-Tags does not scan the content for images, but uses the WordPress API to pick up a suitable image.

In this case the solution would be to enable the the `Global image override` feature in the plugin settings (_Setting -> Metadata -> Metabox features -> Global image override_). And then, in addition to the `<img ... />` elements in the content, add the URL of the image in the relevant field (Global image override) of the _Metadata_ section in the post editing screen. This will force Add-Meta-Tags to use that URL in the metadata and do not use the WP API to pick up an image.

I hope this helps. If you have more questions, please feel free to ask.

George

**Comment by soccermoviemom** [comment]
Hi George,
Thanks for your reply! As u thought, I use the "Add Media" button in the Wordpress editor to insert my thumbnail images. Most of my media links are to movie images stored on tmdb.org, maybe 10% are stored in the wp media library. I don't add the images as default images for the post because they ended up too large that way. You are right, the html ends up looking like this: 
     <img class="alignleft" src="https://image.tmdb.org/t/p/w396/2bGyIbqhbEni8rumbpjZq20QehP.jpg" 
     alt="Bounce: How the Ball Taught the World to Play (2015)" width="139" height="206" />

I will try what u suggest.
-mj

**Comment by gnotaras** [comment]
@soccermoviemom

Hi Merijane, have you resolved the issue? Should I close this ticket?

George

**Comment by soccermoviemom** [comment]
Sorry for the delay. I'm working on it right now

**Comment by soccermoviemom** [comment]
THANK YOU, that was outstanding, it worked!
I only did one post Fahrenheit-2010 as a test and will use this going forward as I post new items and announce them on Twitter.

One more question, I looked at your microdata function and thought I might instead insert a few bits of microdata myself manually. This is because I have already manually generated JSON-LD script for all my posts and which i put in the header using another plugin. Do you know if it's ok to use both microdata and JSON-LD on the same post? 

Thank you again for your help, I will reply on github as well (but without this extra question).
-mj Lee

**Comment by soccermoviemom** [comment]
Sorry George I didn't realize that replying in email automatically posted to github.

**Comment by gnotaras** [comment]
No problem Merijane! Glad you have sorted it out!
