### ISSUE TITLE
Site-wide META tags in the top of the page

### ISSUE THREAD

**Issue by daniushko** [gnotaras/wordpress-add-meta-tags#25]
Hello,

I installed you nice plugin 2 days ago. Yesterday while setting it up I wrote some data in Site-wide META tags field. After saving the changes the text appered on the top of my page dividing the menu top bar in two. Is that the way it works or it's a bug?
![meta tags problem](https://cloud.githubusercontent.com/assets/16694423/12312314/613efdf6-ba56-11e5-8e12-7206b8166969.jpg)

**Comment by gnotaras** [comment]
Hello @daniushko,

Thanks for your feedback.

Yes, this is normal. This box expects complete `meta` or `link` elements (HTML code). For instance:

```html
<meta name="google-site-verification" content="1234567890" />
<meta name="msvalidate.01" content="1234567890" />
```

These are added in the `<head>` section of your HTML page. If you enter plain text in this section, the web browser displays it exactly as shown in the image.

By pressing the `Help` button on the top right corner of the screen you can access the integrated help, which contains examples and more info.

Admittedly, the documentation needs some more attention, but the time is really limited at the moment.

Hope this helps!

I'm going to close this issue. If you still have questions, please feel free to ask.

Best Regards,
George
