### ISSUE TITLE
do_shortcode

### ISSUE THREAD

**Issue by kunicz** [gnotaras/wordpress-add-meta-tags#30]
Is there any filter or hook to parse description content through do_shortcode function? If there is no any it would be nice to add this functionality. I have a shortcode in text, but add-meta-tags-plugin ignores shortcodes. Thenk you

**Comment by gnotaras** [comment]
Hi, thank you for your feedback.

Could you try adding the following code snippet in the theme's `functions.php` file and let me know if it fixes the issue?

```php
function amt_force_post_content_shortcode_expansion($post_content, $post) {
    return do_shortcode( $post_content );
}
add_filter('amt_get_the_excerpt_initial_content', 'amt_force_post_content_shortcode_expansion', 10, 2);
```

This enforces the expansion of the shortcodes in the initial content that is passed to description generator.

Kind Regards,
George

**Comment by kunicz** [comment]
Yes. Thank you. This did the magic.
I inspected your code and found a lot about content cleaning in amt-utils.php and I definitely saw this filter, but didn't get the clue by myself. Thank you for applying filters in plugin - it is very handy!

**Comment by kunicz** [comment]
Maybe for the future it would be usefull to separate user shortcodes from wp shortcodes like [gallery] or even make the ability to set allowed shortcodes when all other will be stripped.

**Comment by gnotaras** [comment]
Thanks for letting me know it worked! Yep, a decision has to be made at some point about how to handle shortcodes when generating an automatic description. Should they be stripped or expanded or go ahead according to some pre-defined rules such as the 'allowed shortcodes' concept as you suggested? Needs some thought, but this is a very good idea. Thanks!

George

**Comment by gnotaras** [comment]
I'm thinking about adding an option in the settings which would force the shortcodes to be expanded before generating an automatic description. I think this is the only solution that would make sense for most users. Having the plugin take a decision by itself will most probably lead to problems. This will possibly be implemented for the next release. I'll keep you updated.

**Comment by gnotaras** [comment]
An option has been added in 2.10.8. Thanks for your feedback!

George

**Comment by nguyenhanhbka55** [comment]
Hi gnotaras,
I'm also have problem same  like kunicz. I can handle by extend your plugin, then write before code paragraph (addtional to add_filter()). Please let me know how this possible?
Thank you so much.
