### ISSUE TITLE
Impossible to have only manual meta descriptions

### ISSUE THREAD

**Issue by chesio** [gnotaras/wordpress-add-meta-tags#33]
Hi George,

I want only manual meta descriptions to be output by the plugin, but I found out that unless I check "Automatically generate the description meta tag" box, no meta descriptions for single posts/pages are printed out at all. By manual meta description I mean text entered into "Description" metabox.

I checked the code and this [if-condition](https://github.com/gnotaras/wordpress-add-meta-tags/blob/master/metadata/amt_basic.php#L401) that basically checks if [auto_description option is set](https://github.com/gnotaras/wordpress-add-meta-tags/blob/master/metadata/amt_basic.php#L64) seems to confirm my observation.

Is this intended change? I'm almost sure it was possible to display only manually entered meta descriptions in older versions of the plugin. I'm using version 2.10.7 of the plugin with WordPress 4.1.1.

Greets,
Česlav

**Comment by gnotaras** [comment]
Hi Česlav,

Thanks for your feedback.

I've received conflicting feedback about this functionality and by convention it is as of now. As soon as I find some time I'll take a closer look at the code and see if it is possible to achieve the functionality you want using the current filters.

Kind Regards,
George

**Comment by gnotaras** [comment]
> I'm almost sure it was possible to display only manually entered meta descriptions in older versions of the plugin.

IIRC, this might be the case in very old versions of the plugin (I think pre 2.X). One of the main reasons this functionality ended up as of now is that if the plugin did not do automatic descriptions, it would also break opengraph and twitter cards metadata as the relevant and required description meta tag (`og:description` and `twitter:description`) would be missing.

However, I took a closer look at the code and I noticed that I had added two filter hooks for this purpose for the description and keywords:

* https://github.com/gnotaras/wordpress-add-meta-tags/blob/master/amt-utils.php#L708
* https://github.com/gnotaras/wordpress-add-meta-tags/blob/master/amt-utils.php#L755

You could try adding the following snippet in `functions.php`:

```php
add_filter( 'amt_generate_description_if_no_manual_data', '__return_false' );
add_filter( 'amt_generate_keywords_if_no_manual_data', '__return_false' );
```

Please note I haven't tested them. I'd appreciate your feedback if you try it. I'll also test them at some later time and provide more details.

George

**Comment by gnotaras** [comment]
According to my tests, the above filter based switches do the trick. Please note that this also affects the rest of the metadata and should only be used if you know exactly what you are doing.

Apart from the above switches there are no plans to alter the current functionality. Of course, I'm always open to new ideas and suggestions for improvements. Your feedback is welcome and much appreciated.

Please let me know if I can close this issue.

George

**Comment by chesio** [comment]
Hi George,

Thanks for quick response, clarification and hint about filters - I'm going to use them, they work fine in my scenario.

I have one suggestion though: what got me confused is that Description field is visible in Metadata metabox whenever the corresponding checkbox is checked in settings. But unless automatic meta description/Open Graph/Dublin Core metadata are on, the description entered manually has nowhere to display. Also, the message below the field about automatic description being used when none is entered is not true in such case. Maybe it would be worth to hide the field or replace it with message along the lines: "You have custom description switched on, but you have no metadata generator active that could use it - please review your settings".

Anyway, feel free to close the issue :)

Česlav

**Comment by gnotaras** [comment]
Good point about the help message Česlav! I'll try to fix it in one of the future releases.

About the 'description' field in the Metadata metabox, this is enabled as long as the relevant metabox feature (Custom description) has been enabled in the 'Settings -> Metabox Features'. This behavior is like all other Custom Fields, which are still displayed in the post edit screen, regardless of the fact they might not be used or displayed in the theme. Please correct me if I'm missing anything or if I misunderstood your comment.

I'll leave the issue open and also mark it as a bug to remind me to fix the help text.

Thanks for your feedback. :)

George

**Comment by chesio** [comment]
Hi George, you got me right. I think changing the help text can prevent some confusion - would definitely do in my case :)

Glad I could help!
Česlav

**Comment by gnotaras** [comment]
Hi Česlav, I'm working on this issue and changing the help messages will result in over-complicated logic, since these help messages are already different according to the post type of the object that is being edited.

So, for now and since this is unsupported functionality, I'll go ahead with the addition of a warning under the current message. For instance:

_Warning: the automatic generation of descriptions has been turned off._

I hope this is fine for now.

George

**Comment by gnotaras** [comment]
Fixed. I will now close the issue. Please feel free to add more feedback or reopen it. Thanks for the issue report!

George
