### ISSUE TITLE
Facebook opengraph

### ISSUE THREAD

**Issue by daniushko** [gnotaras/wordpress-add-meta-tags#35]
Hello George,

Please accpet my appologies for botehring you again!
As you may alredy noticed I'm not an experienced user so I need yoyur hlp againa and hopefully my question is not very stupid.
I did my first post in wordpress and when I decided to see how it will be shared in fb I realized that it shows my home page tags, but not the post I'm sharing. With twitter and google+ it seems OK. I tried to find a solution without success (I'm not sure where to write the custom opengraph tags), but I'm not sure what I have to do, while it doesn't work only with facebook. I tried the debugger and that's what I got:

Inferred Property	The 'og:url' property should be explicitly provided, even if a value can be inferred from other tags.
Inferred Property	The 'og:title' property should be explicitly provided, even if a value can be inferred from other tags.
og:image could not be downloaded or is too small	og:image was not defined, could not be downloaded or was not big enough. Please define a chosen image using the og:image metatag, and use an image that's at least 200x200px and is accessible from Facebook. Image 'http://swansphotography.com/wp-content/uploads/Featured-picture-by-photographer-Daniel-Ahchiev_007.jpg' will be used instead. Consult http://developers.facebook.com/docs/sharing/webmasters/crawler for more troubleshooting tips.

The url I'm tring to share is http://swansphotography.com/10-questions-to-ask-your-wedding-photographer/

Please advice me how to proceed! And thank you in advance!

Best,

Daniel

**Comment by gnotaras** [comment]
Hi Daniel,

In the Facebook Debug Tool, just click on _Fetch new scrape information_ so that the debugger fetches the page again. Otherwise the report is based on Facebook's cached copy, which was probably stored at a time that the opengraph metadata generator was not enabled on your web site.

I did it and the preview of the shared item shows just fine. I still get a warning: _og:image could not be downloaded or is too small_. But this might have to do with your server or network load.

I see no problem here.

Best Regards,
George

**Comment by gnotaras** [comment]
Also there is this warning:

```
The app id (1704978226383073) in fb:app_id metatag is invalid. The default app id (966242223397117) will be assigned instead when this URL is shared to Facebook.
```

You have probably added an invalid app id in a meta tags in the full meta tags box.

George

**Comment by gnotaras** [comment]
Hi Daniel, I'm going to close this issue since it involves no problem related to the plugin (I'm cleaning up the issues as I prepare for a new release). Nevertheless, please feel free to add more feedback to it.

Best Regards,
George

**Comment by daniushko** [comment]
All is OK now George. Thank you so much! Perfect as always!

Best,

Daniel

P.S. Where are you from?

**Comment by gnotaras** [comment]
> P.S. Where are you from?

Hi Daniel, I'm from Greece living in Thessaloniki.

Best Regards,
George

**Comment by daniushko** [comment]
Bless you! :)
I'm from Bulgaria, but I live in UK. My mother lives in Athens and I'm flying there in 2 days :)

**Comment by gnotaras** [comment]
That's awesome! By the way, excellent photography! :+1:

**Comment by gnotaras** [comment]
Hello Daniel, thanks for the kind review! It's much appreciated! :)

**Comment by daniushko** [comment]
You're welcome! It's more than deserved!
