### ISSUE TITLE
qTranslate X issue

### ISSUE THREAD

**Issue by kunicz** [gnotaras/wordpress-add-meta-tags#36]
Hello again.
I use qTranslate X (2 languages) on the site and in most cases AMT works pretty well with multilingual content: titles, site title and others translated well.
But one thing is never translated. The post-type:PAGE meta description is always in default lang. It is very strange because post-type:POST meta description translated well. Do you use different approaches to get these texts?
I do not ask you to implement the qTranslate X to AMT. I am really wondering where is the difference between post and page in amt and why so?
Thank you.

**Comment by gnotaras** [comment]
Hi @kunicz,

Thanks for your feedback.

I'm really out of ideas why this might be happening. The custom description is processed in the same way for all post objects (posts, pages and custom post types). It should work exactly the same as with posts.

I'm not using qTranslate-X at the moment in any test web site, but I'll add a note in my bug tracker to test it at some point in the future.

George

**Comment by HowToSolutions** [comment]
The way I make this plugin compatible with qTranslate-X is by modifying a single line in amt-utils.php fie.

Original code:
`$initial_content = apply_filters( 'amt_get_the_excerpt_initial_content', $post->post_content, $post );`

I just wrap $post->post_content with __() function, like so:
`$initial_content = apply_filters( 'amt_get_the_excerpt_initial_content', __($post->post_content), $post ); `

After that, the meta description always contains the correct language.

**Comment by HowToSolutions** [comment]
The way I make this plugin compatible with qTranslate-X is by modifying amt-utils.php fiie in two places.

One is needed in cases where post/page uses meta description box and the other is used when that meta description box is empty and content is used instead. I think that is what @kunicz is noticing.

Below are my modifications, that I need to add every time the plugin updates. It would be nice, if this would be included in future version of add meta data.

First line that I modifiy is:
`$initial_content = apply_filters( 'amt_get_the_excerpt_initial_content', $post->post_content, $post );`

I just wrap $post->post_content with __() function, like so:
`$initial_content = apply_filters( 'amt_get_the_excerpt_initial_content', __($post->post_content), $post ); `


Second modification is located in `amt_get_content_description` function. 
Here I just make sure, the returned variable is also wrapped with __() function, like so:
  `return __($content_description);`

After changes to those two lines, the meta description always contains the correct language.

**Comment by gnotaras** [comment]
Hi @HowToSolutions 

This is very interesting. Thanks for posting it. I'll take a closer look at the code and see why passing the variable through `__()` is required for the description and reply back in the following days.

Does this issue only occur with the description and not with any other field of the _Metadata_ metabox?

George

**Comment by HowToSolutions** [comment]
I only use meta description so I only focused on that part of plugin to work. For other fields I'm guessing it needs similar fix.

The way qTranslate uses [__() function](https://codex.wordpress.org/Function_Reference/_2) is that it filters original text which is wrapped with language tags and returns only text for current language. 

This is quote from original qTranslate webpage:

> Multilingual Text in Templates without the need to change Gettext Databases/.mo files – Use Language Tags with Gettext!

So if we have code like this:
```
$mytext="<!--:en-->english text<!--:--><!--:de-->german text<!--:-->";
echo __($mytext);
```

When webpage is in English, the qTranslate will filter that variable and returned **english text** and when in German, it will returned **german text**.
If qTranslate is not installed, __() returns original text.

Also check [this](https://codex.wordpress.org/I18n_for_WordPress_Developers) Codex page about  translating a plugin and about gettext function.

**Comment by gnotaras** [comment]
> What qTranslate does is it hooks into __() function and it filters original text which is wrapped with language tags and returns only text for current language.

Oh, I see. Very useful piece of information. I'll look into this more closely and fix any issues.

**Comment by gnotaras** [comment]
Hello all,

Could you please check if it works as expected by adding the following in the theme's `functions.php` file?

```php
function amt_q_translate_x_workaround_description($data) {
    return __($data);
}
add_filter('amt_get_the_excerpt_initial_content', 'amt_q_translate_x_workaround_description');
```

Also, feedback about whether custom keywords and custom title work as expected would very useful. I'll also try to test q-translate-X myself very soon.

**Comment by gnotaras** [comment]
Right now it's difficult to tell if wrapping the post content through `__()` could cause any problems with other multilingual plugins. Some time for testing will be required before such a change makes it into the plugin.

In the meanwhile, using workarounds like the above should be preferred instead of modifying the plugin files directly.

I'll reply back with some more info soon.

George

**Comment by HowToSolutions** [comment]
Opps, I totally missed that the first line I modified contains `appy_filter `function. I tried that filter now and it works. 

You are right, it is more safe to use filters for `__()`. 
So to make this plugin compatible with qTranslate, all that is needed is to add additional `apply_filter` functions where it is needed.

For example the second modification I made located in `amt_get_content_description` function where i wrapped line `return $content_description;` with `__()` does not have any `apply_filter`. 

I tried language tags on custom title and custom keyword in posts and that seems to be working.

**Comment by gnotaras** [comment]
Right. Sorry, forgot about `amt_get_content_description()`. Also made a small mistake in the above snippet.

The current post contains the most up to date information.

The required filter hook in `amt_get_content_description()` will be available in the next release. The [changeset](https://bitbucket.org/gnotaras/wordpress-add-meta-tags/commits/31d12b616d4536768f5edb8341bd3f746ee16ebc) is here.

The required extra code is the following:

```php
// qTranslate-X workaround for the initial content for auto-generated description generator.
function amt_q_translate_x_workaround_autogen_description($data, $post) {
    return __($data);
}
add_filter('amt_get_the_excerpt_initial_content', 'amt_q_translate_x_workaround_autogen_description', 10, 2);

// qTranslate-X workaround for the final description
function amt_q_translate_x_workaround_final_description($data, $post) {
    return __($data);
}
add_filter('amt_get_content_description', 'amt_q_translate_x_workaround_final_description', 10, 2);
```

> I tried language tags on custom title and custom keyword in posts and that seems to be working. 

Thanks for testing this. It is much appreciated. I might have an idea why this is happening with the description but I'm not 100% sure.

Anyway I'll try to test the above snippet with other multilingual plugins and, if there are no conflicts, I'll possibly incorporate the aforementioned changes in the plugin.

Thank you for your feedback. It has been very helpful and right to the point.

George

**Comment by kunicz** [comment]
`function amt_q_translate_x_workaround_description($data) {
    return __($data);
}
add_filter('amt_get_the_excerpt_initial_content', 'amt_q_translate_x_workaround_description');`

This works for me either!

**Comment by gnotaras** [comment]
Hi @kunicz 

Thanks for your feedback. Most probably both filtering functions will be needed. This will be possible in 2.10.10 which will be out very soon.

George

**Comment by HowToSolutions** [comment]
Thank you. I'm looking forward to the new version.

**Comment by gnotaras** [comment]
I'm looking again into this issue. I'm interested in integrating the solution in the plugin so you don't have to use any filters, but before doing so I have to make sure about what works and what not.

So far the solution is to use the `__()` function at the points indicated above, but according to my research such use of that translation function might not be the optimal solution.

An alternative could be the `qtranxf_useCurrentLanguageIfNotFoundUseDefaultLanguage()` function. Instead of the above snippet, could you please check if the following could work?

```php
add_filter('amt_get_the_excerpt_initial_content', 'qtranxf_useCurrentLanguageIfNotFoundUseDefaultLanguage');
add_filter('amt_get_content_description', 'qtranxf_useCurrentLanguageIfNotFoundUseDefaultLanguage');
```

If this works, I'll integrate it inside the plugin.

Unfortunately, I'm not familiar with qtranslate-X and currently there is no time to test it. Your feedback is much appreciated.

Another alternative could be shipping a JSON-encoded configuration file as described in the following:

 * https://qtranslatexteam.wordpress.com/integration/
 * https://qtranslatexteam.wordpress.com/json-configuration-syntax/

It'll need some studying, but seems like a decent solution.

Thanks for your feedback in advance.

George

**Comment by HowToSolutions** [comment]
Hi,

Sorry for the late reply.

I tried to use `'qtranxf_useCurrentLanguageIfNotFoundUseDefaultLanguage'` in `add_filter` and it work too.

**Comment by gnotaras** [comment]
Hi, I decided to no longer offer support for this plugin. I'm very sorry about that. I'll now close this issue. Please use any workaround you see fit.

**Comment by HowToSolutions** [comment]
I'm sorry to hear that. Could you at least leave those two filters `'amt_get_the_excerpt_initial_content' ``and 'amt_get_content_description'` in your plugin? That way, the developers can still make add-meta-tags plugin qTranslateX compatible.

**Comment by HowToSolutions** [comment]
I'm sorry to hear that. I really liked your plugin. It was simple and it did what it promised. 

I appreciate all the work and time you have put into add-meta-tag and wish you very best on other projects.

**Comment by gnotaras** [comment]
Hi, thanks. Same to you! :) Made another release to fix a small issue with the release tags and pushed it on here.
