### ISSUE TITLE
tag shows up twice

### ISSUE THREAD

**Issue by arpeerp** [gnotaras/wordpress-add-meta-tags#42]
Hello,

I use Add Meta Tags for WordPress and on every page the tags are fine.
But on one page the tag <meta name="description" shows up twice.
Once with the tags i filled in, but also one with text as showing on the page.
And that i don't think is the correct way of tagging.

Help appreciated.

Regards,

arpeerp

**Comment by gnotaras** [comment]
Hello Arpeerp,

Add-Meta-Tags generates a single _description_ plugin. I suspect that the second one is hard coded in the theme templates and appears in a specific archive or other specific part of the web site. If you provide more information about where it appears, I'll be able to help more with locating the exact template.

The point is that the plugin is not responsible for this issue. I highly recommend contacting the theme developer.

I will mark this issue as invalid, but this is for categorization purposes only. You did very well to report it.

Kind Regards,
George

**Comment by arpeerp** [comment]
Hello George,

Sorry I was to soon to ask for help. I solved the "problem".

The plugin has an option "Basic Metadata" with "Automatically generate the description meta tag."
I disabled this option because at the "Site-wide META tags" I already used the mentioned tag.

The plugin has many configuration options and in the haste I missed this one. Again sorry.

Regards,

arpeerp

**Comment by gnotaras** [comment]
Hello Arpeerp,

Oh, I see. Thanks for letting me know that you have sorted this out.

I will now close this issue. Thanks for your feedback.

George
