### ISSUE TITLE
Picture metadata population issue and FB:App_ID warning

### ISSUE THREAD

**Issue by andrewarthurdawson** [gnotaras/wordpress-add-meta-tags#43]
Hello George, I figured you would want me to add this error out here for everyone to see. I sent you an email as well. I have two add meta data issues going on.

1. The first is that I have a posting that went through tonight at 6pm. The URL is:

http://thetwelfthstep.com/2016/03/04/grand-cayman-vacation-day-3/

I have a picture associated to this blog entry. If you open the link and go to the bottom of it you will see it's a beach picture. Yet, when I type in the URL in the Facebook debugger and when I place in the URL in the Add Status on Facebook, I get the picture that is the normal default of my website, that comes from the field in your add meta data plugin (the default picture field). I have no idea why this is doing it. I'm not sure how to remedy this?

UPDATE: After multiple fetching new scrapes and a few hours after my posting, it finally was getting the right image. Now it seems to be populating correctly. What would have caused this image to not show up for the few hours it didn't?

2. Also, the second issue is that I am getting a warning on all of my Facebook Meta Data debugger issues that says:

Share App ID Missing	The 'fb:app_id' property should be explicitly provided, Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog.

Do you have any idea how to remedy this? Do I need to add a SiteWide Meta Data field for this like I did for FB:Admins when you had me do that 2 years ago?

Thanks for any help in this! :)
Andrew

**Comment by gnotaras** [comment]
Hello Andrew,

> UPDATE: After multiple fetching new scrapes and a few hours after my posting, it finally was getting the right image. Now it seems to be populating correctly. What would have caused this image to not show up for the few hours it didn't?

Hmm, I'm out of ideas why this might have been happening. From what I see, the link to the `full` image size is included in the `og:image` meta tag and the image is big enough, so there is no problem with its size. Facebook should have picked it up without problems on the first try. I have no explanation, apart from the possibility that it was a possible temporary problem.

Also, please take a look at the following page which outlines the best practices of sharing images on FB:

https://developers.facebook.com/docs/sharing/best-practices#images

> Also, the second issue is that I am getting a warning on all of my Facebook Meta Data debugger issues that says:
>
> Share App ID Missing The 'fb:app_id' property should be explicitly provided, Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog.
>
> Do you have any idea how to remedy this? Do I need to add a SiteWide Meta Data field for this like I did for FB:Admins when you had me do that 2 years ago?

About the second issue, this is about the missing Facebook App ID. This App ID is a number which you include in a meta tag like the following and add it in the `Site-Wide Meta Tags` box in the the plugin settings page at `Settings-Metadata`:

```
<meta property="fb:app_id" content="1234567890" />
```

A step by step guide can be found here:

https://developers.facebook.com/docs/apps/register

I hope these help. Please feel free to post any questions.

George

**Comment by gnotaras** [comment]
Hi Andrew,

Since we further discussed about this issue over email, I'm going to close it now.

Thanks for your feedback. I'll point anyone having a similar question to my reply above.

George
