### ISSUE TITLE
Importing from other plugins

### ISSUE THREAD

**Issue by Gnomag** [gnotaras/wordpress-add-meta-tags#45]
Hi, I am fed up with all the conflicts I keep getting from YOAST SEO so I have decided to try another plugin.

My first question is; How do I import my YOAST Meta Tags, description, titles etc.

Is this possible? I don't want to be rewriting 200 pages :(

Waiting patiently for an answer.

Gnomag

**Comment by gnotaras** [comment]
Hi,

There are various ways to migrate your data, but at this time all of them require a very little amount of manual work.

Please see [this comment](https://github.com/gnotaras/wordpress-add-meta-tags/issues/6#issuecomment-154217229) of mine which outlines all the available methods.

Currently, my recommendation is to make the required [small modification](https://wordpress.org/support/topic/add-meta-tags-not-finding-any-records?replies=6#post-6408619) to the SEO Data Transporter plugin and use it for data migrations.

For more information, the relevant page on the wiki is this: http://www.codetrax.org/projects/wp-add-meta-tags/wiki/Migrate_to_Add-Meta-Tags

Another alternative is that you can test Add-Meta-Tags without migrating your data. You just have to instruct it where to find your current description/keywords/titles.

This can be done by adding a code snippet like the following in the theme's `functions.php`. Please make sure to replace `_x_description`, `_x_keywords` and `_x_title` with the respective field names used by your current plugin. Unfortunately, I cannot provide any help with the field names. Please find this information from the developers.

```php
function read_plugin_x_description_field( $extfields, $post_id ) {
    array_unshift( $extfields, '_x_description' );
    return $extfields;
}
add_filter( 'amt_external_description_fields', 'read_plugin_x_description_field', 10, 2 );

function read_plugin_x_keywords_field( $extfields, $post_id ) {
    array_unshift( $extfields, '_x_keywords' );
    return $extfields;
}
add_filter( 'amt_external_keywords_fields', 'read_plugin_x_keywords_field', 10, 2 );

function read_plugin_x_title_field( $extfields, $post_id ) {
    array_unshift( $extfields, '_x_title' );
    return $extfields;
}
add_filter( 'amt_external_title_fields', 'read_plugin_x_title_field', 10, 2 );
```

Please note that by using the above snippet, Add-Meta-Tags uses the configured fields of 3rd party plugins as *read-only* sources of information. Add-Meta-Tags will never write to them. If you make any modifications to descriptions, keywords or titles while the above snippet is in effect, the modification will be written to the respective Add-Meta-Tags custom fields.

If you have more questions, please feel free to ask.

Time permitting I intend to do some extra research about how to facilitate this process. The SEO Data transporter plugin seems dated and the developer cannot be easily reached. Some users have provided me with alternative code, but I still have to find the time to make the best use of it for the benefit of users.

Kind Regards,
George

**Comment by Gnomag** [comment]
Thankyou George for not only a very quick response but for such concise instructions. Seems like a bit of work for a novice like me but this is the only way I am going to learn :)

I look forward to using your plugin.

**Comment by gnotaras** [comment]
Please let me know if you encounter any difficulties. Making the required modifications to the SEO data transporter plugin is easier than it seems.

George
