### ISSUE TITLE
Notices with WooCommerce

### ISSUE THREAD

**Issue by dima-stefantsov** [gnotaras/wordpress-add-meta-tags#46]
PHP Error	Count	Location	Call Stack	Component
Notice

Undefined property: stdClass::$post_content	1	wp-content/plugins/add-meta-tags/amt-utils.php:303	amt_get_clean_post_content()
 wp-content/plugins/add-meta-tags/amt-utils.php:358
amt_get_the_excerpt()
 wp-content/plugins/add-meta-tags/amt-utils.php:756
amt_get_content_description()
 wp-content/plugins/add-meta-tags/metadata/amt_basic.php:443
amt_add_basic_metadata_head()
 wp-content/plugins/add-meta-tags/add-meta-tags.php:274
amt_get_metadata_head()
 wp-content/plugins/add-meta-tags/add-meta-tags.php:320
amt_add_metadata_head()
 wp-content/plugins/add-meta-tags/add-meta-tags.php:351
amt_print_head_block()
 Unknown location
do_action('wp_head')
 wp-includes/general-template.php:2434
wp_head()
 wp-content/themes/hueman/header.php:10
load_template('~/wp-content/themes/hueman/header.php')
 wp-includes/template.php:521
locate_template()
 wp-includes/general-template.php:45
get_header('shop')
 wp-content/plugins/woocommerce/templates/archive-product.php:22	Plugin: add-meta-tags

Undefined property: stdClass::$post_date	1	wp-content/plugins/add-meta-tags/amt-utils.php:3613	amt_internal_get_title()
 wp-content/plugins/add-meta-tags/amt-utils.php:3541
amt_get_title_for_metadata()
 wp-content/plugins/add-meta-tags/metadata/amt_opengraph.php:194
amt_add_opengraph_metadata_head()
 wp-content/plugins/add-meta-tags/add-meta-tags.php:277
amt_get_metadata_head()
 wp-content/plugins/add-meta-tags/add-meta-tags.php:320
amt_add_metadata_head()
 wp-content/plugins/add-meta-tags/add-meta-tags.php:351
amt_print_head_block()
 Unknown location
do_action('wp_head')
 wp-includes/general-template.php:2434
wp_head()
 wp-content/themes/hueman/header.php:10
load_template('~/wp-content/themes/hueman/header.php')
 wp-includes/template.php:521
locate_template()
 wp-includes/general-template.php:45
get_header('shop')
 wp-content/plugins/woocommerce/templates/archive-product.php:22	Plugin: add-meta-tags

Undefined property: stdClass::$post_date	1	wp-content/plugins/add-meta-tags/amt-utils.php:3614	amt_internal_get_title()
 wp-content/plugins/add-meta-tags/amt-utils.php:3541
amt_get_title_for_metadata()
 wp-content/plugins/add-meta-tags/metadata/amt_opengraph.php:194
amt_add_opengraph_metadata_head()
 wp-content/plugins/add-meta-tags/add-meta-tags.php:277
amt_get_metadata_head()
 wp-content/plugins/add-meta-tags/add-meta-tags.php:320
amt_add_metadata_head()
 wp-content/plugins/add-meta-tags/add-meta-tags.php:351
amt_print_head_block()
 Unknown location
do_action('wp_head')
 wp-includes/general-template.php:2434
wp_head()
 wp-content/themes/hueman/header.php:10
load_template('~/wp-content/themes/hueman/header.php')
 wp-includes/template.php:521
locate_template()
 wp-includes/general-template.php:45
get_header('shop')
 wp-content/plugins/woocommerce/templates/archive-product.php:22	Plugin: add-meta-tags

Undefined property: stdClass::$post_date	1	wp-content/plugins/add-meta-tags/amt-utils.php:3619	amt_internal_get_title()
 wp-content/plugins/add-meta-tags/amt-utils.php:3541
amt_get_title_for_metadata()
 wp-content/plugins/add-meta-tags/metadata/amt_opengraph.php:194
amt_add_opengraph_metadata_head()
 wp-content/plugins/add-meta-tags/add-meta-tags.php:277
amt_get_metadata_head()
 wp-content/plugins/add-meta-tags/add-meta-tags.php:320
amt_add_metadata_head()
 wp-content/plugins/add-meta-tags/add-meta-tags.php:351
amt_print_head_block()
 Unknown location
do_action('wp_head')
 wp-includes/general-template.php:2434
wp_head()
 wp-content/themes/hueman/header.php:10
load_template('~/wp-content/themes/hueman/header.php')
 wp-includes/template.php:521
locate_template()
 wp-includes/general-template.php:45
get_header('shop')
 wp-content/plugins/woocommerce/templates/archive-product.php:22	Plugin: add-meta-tags

**This happens on front page, main woocommerce page set as front page.**

Template: /public_html/wp-content/plugins/woocommerce/templates/archive-product.php
is_archive()
is_front_page()
is_page()
is_post_type_archive()

**Comment by gnotaras** [comment]
Hello Dima,

I could replicate the problem. I'll try to look into it as soon as possible and reply back.

Best Regards,
George

**Comment by gnotaras** [comment]
It seems WooCommerce's main shop page is not a regular `WP_Post` object and thus the `$post->post_date` attribute cannot be found. In such a case, I'm thinking of resolving it by setting the `#year#`, `#month#`, `#month_name#` and `#day#` template variables according to the *current* date. Alternatively, those variables could be left having an empty value or zero and let the user make a decision about their value while customizing the titles. This will need some thought.. Any suggestion would be much appreciated.

About the missing `$post->post_content` attribute, there is very little I can do apart from adding a check. In case of such an irregular post object, No automatic description will be generated, but the user will have to either add a custom description or an excerpt manually.

I'll try to fix them at some later time tonight and push the changes to the repositories. I've planned a new release in the following days, but I'll see if it will be possible to roll it out sooner.

George

**Comment by gnotaras** [comment]
Clarification:

> It seems WooCommerce's main shop page is not a regular `WP_Post` object

This seems to be happening only when the WC main shop page is used as the static front page. In this case the post object as returned by `get_queried_object()` is not useful for AMT.

A workaround for the time being could be the following:

```php
function amt_fix_wc_front_page_post($default) {
    if ( is_front_page() ) {
        global $post;
        return $post;
    }
    return $default;
}
add_filter('amt_get_queried_object', 'amt_fix_wc_front_page_post');
```

The final resolution will need some more thought.

George

**Comment by gnotaras** [comment]
Please disregard that last workaround. The global `$post` object seems to be the first product listed on the page, which is not what we need.

It seems the main WC shop page, when used as the front page, behaves like WP's default posts page and not like a static page.

**Comment by gnotaras** [comment]
Fixed in ee13529d3c6c8381844a6ba9aee5503ca613a3ee

Finally made up my mind and the date related template variables are left empty or zero. It's very easy for the user to use the current date in the title templates.

George

**Comment by gnotaras** [comment]
@dima-stefantsov I finally think I've figured out a better (more generic) way to resolve this without checking specific attributes of the post object, but instead by manually setting `$post` to the correct `WP_Post` object as needed by AMT. This is much like the problem with Anspress, but for a very specific case.

**Comment by gnotaras** [comment]
Hi Dima,

Apart from these notices there are some other things related to the title of that page. I've outlined them in [this comment](https://github.com/gnotaras/wordpress-add-meta-tags/issues/47#issuecomment-203163584)

Hope it is helpful.

**Comment by gnotaras** [comment]
I will now close this issue. Please feel free to reopen it if needed or add more feedback.

George
