### ISSUE TITLE
AMT grabs parts of Javascript code into og:description meta tag

### ISSUE THREAD

**Issue by its-thomas** [gnotaras/wordpress-add-meta-tags#48]
Hi George,

I just noticed the following issue:

AMT seems to grab parts of the StatCounter Javascript Code (which I inserted on a page and which is not visible in the graphical wordpress editor, see http://statcounter.com/support/knowledge-base/14/) into the metatag:

`<meta property="og:description" content="This sentence is for testing purposes only var sc_project=123456789; var sc_invisible=1; var sc_security=123456789; var scJsHost = ((https: == document.location.protocol) ? https://secure. : http://www.); document." />`

Everything but 

> This sentence is for testing purposes only

 should NOT appear in the metatag.

**Comment by gnotaras** [comment]
Hi Thomas,

Thanks for starting a new ticket. Much appreciated! :-)

This is strange. The content passes through the wp_kses() function with no allowed HTML tags, so the <script> tags should have been removed before a description was generated.

I'll try to look into this ASAP and reply back. Thanks for pointing it out

**Comment by gnotaras** [comment]
It seems that `wp_kses()` just removes the `<script>...</script>` tags leaving the actual script in the post content, so AMT thinks it's just content of the post.. I think we are missing something here.. I'll do some more research and reply back.

**Comment by gnotaras** [comment]
I confirm that this is a bug of the plugin.

`wp_kses()` does not seem to be enough to clean up the contents of the `<script>`/`<style>` tags (not sure why it does that though...). The clean up function needs to be enhanced. I'll make a new release shortly.

Thanks for pointing it out. Good find!

**Comment by its-thomas** [comment]
Great! Looking forward to my second shout-out in the changelog and (of course) the updated AMT version ;-)

**Comment by gnotaras** [comment]
While `wp_kses()` fully cleans up the HTML tags, it still leaves the text that is enclosed in `script` and `style` tags. While this is perfectly safe, it is not what we want when trying to generate a description. I've now used `wp_strip_all_tags()` instead, which according to my tests seems to do what `wp_kses()` did plus removing the contents of the aforementioned tags.

Btw, this gave me the opportunity to rework on the logic of the clean up function a bit and make it more complete.

Thanks for your feedback!

**Comment by gnotaras** [comment]
Thomas, I've pushed the 2.10.11 release. According to my tests it should now work in all cases, including cases in which the extra HTML/JS/CSS is added via shortcodes.

I'll leave this issue open until I receive your confirmation that the description is generated properly.

Thanks! :-)

**Comment by its-thomas** [comment]
George, I just tested it on a WooCommerce product page as well as on a regular page, both with very little text and the statcounter JS code. In both cases og:description is fine (no JS code pieces).

Thanks :-)

**Comment by gnotaras** [comment]
Thank you Thomas! In my tests it also works as expected, so I will now close this issue.
