### ISSUE TITLE
Deprecated function call in Add Meta Tags v. 2.10.11

### ISSUE THREAD

**Issue by seancojr** [gnotaras/wordpress-add-meta-tags#49]
I discovered a deprecated function call in the latest version fo Add Meta Tags.

Source file: add-meta-tags/amt-cli.php

Function call: get_blog_list at line 129:
$blog_list = get_blog_list( 0, 'all' ); 

Deprecated as of WP 3.0.0
The codex suggests the use of wp_get_sites() instead.

**Comment by gnotaras** [comment]
Sebastian, thanks for pointing that out! It will be fixed in the next release.

George

**Comment by gnotaras** [comment]
I'm going to close this issue, since I fixed it for the next release. Thank you for your feedback!
