### ISSUE TITLE
Suggestion for Yoast compatibility

### ISSUE THREAD

**Issue by citysailor** [gnotaras/wordpress-add-meta-tags#50]
Hi, 

I have a situation regarding meta data and hreflang and would like to get your advice. 

I read in other post that your AMT plugin works with other plugins so installed Yoast plugin in order to set up my sitemap. After that, I'm trying to set up meta data and see there are two metadata sections of your AMT and Yoast. If I fill all up in AMT and leave all blank in Yoast, it seems Yoast override title due to their default setting which is fine for my other pages except home. Is it good practice to fill all up in both AMT and Yoast or should I fill only a title in Yoast and leave it blank in AMT? I just filled all same(description, keyword, title) in both of them now and am waiting for Google result. 

I installed my wordpress in English but my domain has .co.jp extension targetting to Japan so typed ja_jp for hreflang tag in your Locale option and checked the following two (hope I did right),
- Automatically set the HTML document's lang attribute according to the locale of the content.
- Enable the generation of a link element with the hreflang attribute.

I've been waiting for a couple of days and still see "Your site has no hreflang tags." in the Google Search Console. 

Please let me know if I'm doing wrong and any advice. Thank you.

**Comment by gnotaras** [comment]
Hi there.

Although your questions show that you have a decent understanding of the things you are talking about, you tend to overcomplicate things which are quite straightforward. I have no idea why this happens, but I'll hereby try to briefly clear those things up.

> I read in other post that your AMT plugin works with other plugins

At the technical level, it is possible to use Add-Meta-Tags with any other plugin without breaking anything in your website. However, in case two plugins offer similar functionality, it is up to you to decide which features you should enable or use in each one of them. I'd be happy to answer any **specific** questions about the Add-Meta-Tags features, but, I'm afraid I cannot provide any kind of advice about which features you should use on 3rd party plugins, as I lack this kind of expertise. So, this particular thing is going to be your own decision based on your own research.

For example, if two plugins offer fields in which you can fill in the same type of information, it is up to you to choose which ones of them to actually fill. Filling the similar fields of **both** plugins does not sound like a wise decision, does it?

> I just filled all same(description, keyword, title) in both of them now and am waiting for Google result. 

By reading your post I assume that you are familiar with checking the HTML source code. May I ask what is your expectation after filling in the same information in the two plugins? Isn't it straightforward that this action is going to result in having duplicate meta tags in your HTML page's `head` section? This is **not** going to help your website.

If this sounds too complicated, I'd recommend to start by activating one plugin at a time and familiarize yourself with the feature set. Once you have a better understanding of your needs, then you could start mixing features of various plugins and generally do what you think is best for your web site. But, as I've already mentioned, I cannot help you with that.

About the title issue you mentioned, you can deactivate the Add-Meta-Tags filters, if you like, by adding the following in your theme's `functions.php` or in a custom plugin:

```php
remove_filter('document_title_parts', 'amt_custom_title_tag', 9999, 1);
remove_filter('wp_title', 'amt_custom_title_tag', 9999, 1);
```

> [...] so typed ja_jp for hreflang tag in your Locale option and checked the following two (hope I did right) [...]

There are examples about the correct form of the locale in the help text just under the setting. Also, you can press the 'Help' button at the top right corner and take a look at the _Locale_ section for more information. `ja_JP` sounds about right, but you should really consult a local internationalization/localization group or ask in the General or the Japanese section of the WordPress forums.

> I've been waiting for a couple of days and still see "Your site has no hreflang tags." in the Google Search Console. 

I think you will have to wait a little bit longer than that. AFAIK, the required time varies from website to website and it could take days or even weeks before the change is reflected in the Webmaster Tools.

Closing this issue, I'd like to emphasize on the importance of studying the feature set of each plugin you activate and always choose the features you enable in each one of them wisely.

**Comment by citysailor** [comment]
Thank you for your reply. I totally agree with you. 

I have been searching as heavily relying on online resources and learning this entire web mechanism. Google webmaster tool is new to me and I'm trying to understand each feature one by one now. Any pro supports like you are very helpful.
