### ISSUE TITLE
Option to change default article type in schema

### ISSUE THREAD

**Issue by Tharic-Nar** [gnotaras/wordpress-add-meta-tags#51]
First of all, thanks for this wonderful plugin.

When using schema, it sets the default page type as 'Article', since this is the most common type people are going to need. When **Express Review** mode is enabled and configured correctly, it changes the default page type to '_Review_' - which is extremely helpful (another indicator for SEO). However, I was wondering if there is a method to assign other article types, as listed at _schema.org_.

The two types I am most interested in are:
[TechArticle](https://schema.org/TechArticle) - this is used to denote a page as a guide
[NewsArticle](https://schema.org/NewsArticle) - may help with news crawlers - but not essential

Can this be set on a post by post basis, such as either with a custom field entry or a drop-down list such as with Express Review?

Many thanks.

**Comment by gnotaras** [comment]
Hi, I decided to no longer offer support for this plugin. I'm very sorry about that. I will now close this issue.
